### ISSUE TITLE
russian language 

### ISSUE THREAD

**Issue by temask88** [nextcloud/officeonline#100]
The online office interface does not open in russian language, despite the fact that the language of the system and profile is set to russian

**Comment by Schluggi** [comment]
I think this is a generally problem. All other languages doesn't work either.

I saw this issue earlier in [this post](https://help.nextcloud.com/t/ms-office-online-server-as-document-editor-in-nextcloud/92407/25) (maybe helpful).

**Comment by serioustk** [comment]
I just also stumbled about this problem.
Seems like language selection is done by setting a cookie.

Workaround: edit the `DcLcid` cookie for your office online domain. Per default it contains `ui=1033&data=1033`. Changing this e. g. to `ui=1031&data=1031` leads to german lanuage.

It would be great if the nextcloud plugin would set this cookie or at least init the office online connection with the nextcloud user language.

**Comment by juliushaertl** [comment]
Needs an additional adjustment to the logic that was implemented for the DC_LLCC mapping introduced in https://github.com/nextcloud/officeonline/pull/148/files

**Comment by juliushaertl** [comment]
I prepared a patch for this issue in https://github.com/nextcloud/officeonline/pull/500

Testing and feedback would be very welcome. You can find details on how to apply a patch at https://docs.nextcloud.com/server/latest/admin_manual/issues/applying_patch.html
