### ISSUE TITLE
New installation no work 

### ISSUE THREAD

**Issue by horonekb** [nextcloud/officeonline#128]
**Describe the bug**
in excludeClickOutsideClasses.js throws an error when Open any office file. The error message in browser console is
![image](https://user-images.githubusercontent.com/5750419/111070589-7e84b100-84e3-11eb-8cbd-9c6bd93591f3.png)

**To Reproduce**
1. Install Office Online 2016 success
2. Install OfficeOnline integration app in nextcloud
3. Configure it.
4. Create any doc and click to file

**Expected behavior**

**Screenshots**

**Client details:**
 - Device: [e.g. iPhone6, desktop]

## Server details

**Operating system**:
Centos 7
**Web server:**
httpd
**Database:**
mysql 8 community
**PHP version:**
7.4
**Nextcloud version:**
21
**Version of the officeonline app**
1.0.3
**Version of Office Online server**
2016 

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"YE4Q355Mt3SqzhZAtFmPWwAAAAM","level":2,"time":"2021-03-14T13:34:23+00:00","remoteAddr":"37.110.83.174","user":"admin","app":"no app in context","method":"GET","url":"/index.php/apps/files/","message":"Invalid data provided to provideInitialState by files","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36","version":"21.0.0.18"}
```

#### Browser log
```
Insert your browser log here, this could for example include:
![image](https://user-images.githubusercontent.com/5750419/111070715-f652db80-84e3-11eb-981f-d42f4a77b148.png)
![image](https://user-images.githubusercontent.com/5750419/111070803-682b2500-84e4-11eb-90d9-0fdb09a83871.png)

```

</details>

**Comment by horonekb** [comment]
https://github.com/nextcloud/nextcloud-vue/issues/1689

**Comment by horonekb** [comment]
![image](https://user-images.githubusercontent.com/5750419/111070927-f2738900-84e4-11eb-9b7e-674f62537a69.png)

**Comment by andyxheli** [comment]
@horonekb is this still an issue? if not can you please close. 

If this similar to https://github.com/nextcloud/officeonline/issues/21 sorry can read the error.

**Comment by juliushaertl** [comment]
This looks like a setup related issue on the Office Online server side. I've also seen this happening in relation to possible TLS 1.2 issues as described in https://github.com/nextcloud/officeonline/issues/21#issuecomment-995226982, however the server event viewer logs should give you further insight.
