### ISSUE TITLE
Powerpoint: Sorry we ran into a problem. Please try again

### ISSUE THREAD

**Issue by TheMrg** [nextcloud/officeonline#140]
### Steps to reproduce
1. Nextcloud add OfficeOnlineServer
2. create new powerpoint file
3. or edit a existing

### Expected behaviour
open powerpoint editor

### Actual behaviour
error message

word and excel works well

see screenshot
<img width="945" alt="officeerrorpowerpoint" src="https://user-images.githubusercontent.com/38321123/115926817-bdfbd100-a483-11eb-9dd3-e6e91d493188.png">

Any Ideas?
Please help. seems be a bug in the plugin.
are there anybody using Nextcloud and PPTX from OOS via this Plugin?

**Comment by andyxheli** [comment]
@TheMrg I was able to replicate this issue on my server is this still an issue ? if not can you please close it ?

**Comment by mpetukhov** [comment]
its may be a session cache on OOS.
And may be TLS1.1 support on IIS https://learn.microsoft.com/en-us/officeonlineserver/enable-tls-1-1-and-tls-1-2-support-in-office-online-server

**Comment by patschi** [comment]
As there're no updates on this issue and it's unclear if issue still exists, I'm closing it for now.

Thanks @mpetukhov for your suggestion on this!
