### ISSUE TITLE
Office online error 

### ISSUE THREAD

**Issue by wwwwiii** [nextcloud/officeonline#15]
**Describe the bug**
cURL error 6: Could not resolve host: https://hostname (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
After trying to open a document.

**To Reproduce**
1. Go to install plugin for office online.
2. i entered the https url
3. after opening the the doc editor i recieved the error above.

**Client details:**
 - OS: win 10 pro
- chrome newest version

## Server details

**Operating system**: Ubuntu server 18 lts

**Web server:** nginx

**Database:**mysql

**PHP version:** 7.2.24

**Nextcloud version:18.0.3

**Version of the officeonline app** newest

**Version of Office Online server** newest

**Comment by juliushaertl** [comment]
I cannot reproduce any issue. How did you enter the url into the settings, with or without the protocol? Can you maybe change your actual hostname to something made up and share the server url you have configured?

**Comment by dartcafe** [comment]
I was just testing this. I was using  https://ownaccount.onmicrosoft.com 
This is from a office365-Account. Not shure if this is supported.

**Comment by juliushaertl** [comment]
Make sure you have the protocol added to your url in the settings.

**Comment by juliushaertl** [comment]
>  This is from a office365-Account. Not sure if this is supported.

Ah and the app only supports on-premise Office Online installations.

**Comment by dartcafe** [comment]
Thought that. But I am not sure, if this is the OP's issue....

**Comment by wwwwiii** [comment]
> > This is from a office365-Account. Not sure if this is supported.
> 
> Ah and the app only supports on-premise Office Online installations.

So office 365 is not supported? because that what i tried!

**Comment by juliushaertl** [comment]
Yep, this is not supported

**Comment by wwwwiii** [comment]
Didn't even know people are still actively self-hosting office online :D

**Comment by juliushaertl** [comment]
Added a more clear note to https://github.com/nextcloud/officeonline/blob/master/README.md#server

**Comment by wwwwiii** [comment]
Should be possible to intergratie with office 365. I personally would prefer nextcloud above sharepoint.

**Comment by juliushaertl** [comment]
It will only be possible if you are able to register for the Office 365 - Cloud Storage Partner Program which from the concept of how the registration works is not aimed for self-hosted on premise solutions like Nextcloud. The WOPI procotol should be the same so it might work, but there will be no support for this from our side. 

Feel free to checkout https://wopi.readthedocs.io/en/latest/ for more details on the requirements.

**Comment by juliushaertl** [comment]
The main issue here is that you need your Nextcloud domain whitelisted in the Office 365 cloud service which they don't allow for regular users.
