### ISSUE TITLE
Replace Travis with GitHub Actions

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/officeonline#164]
Travis has stopped their free service. Please switch to GitHub Actions to continue CI testing. Check the app-tutorial app for some nice examples how to run basic phpunit tests and other things there: https://github.com/nextcloud/app-tutorial/tree/master/.github/workflows

**Comment by nickvergessen** [comment]
Also the drone file

**Comment by azul** [comment]
Looks like php unit is running (at least since a few days). I'll look into the other things that were in travis.

**Comment by azul** [comment]
Okay... so linting, phpunit and building the js are tested already. That's very close to what happened in the travis file and also what i saw in the text apps drone file. So i will close this issue. Feel free to reopen and specify what is missing if i missed something.
