### ISSUE TITLE
.txt and newly created files

### ISSUE THREAD

**Issue by SteelPC** [nextcloud/officeonline#2]
- .txt file can’t be opened (no problems with .md) -> Exception: Could not find urlsrc in WOPI
- No more icons next to the office documents in the " + " menu
- Newly created files can’t be opened “Unable to open file”

**Comment by juliushaertl** [comment]
> .txt file can’t be opened (no problems with .md) -> Exception: Could not find urlsrc in WOPI

Thanks for reporting, see #8 for a fix

> No more icons next to the office documents in the " + " menu

Does it also work after force reload of the files app?

> Newly created files can’t be opened “Unable to open file”

Works fine on my test setup here. Anything in the logs about that?

**Comment by SteelPC** [comment]
`.txt file can’t be opened (no problems with .md) -> Exception: Could not find urlsrc in WOPI

Thanks for reporting, see #8 for a fix`

Didn't see any changes

`Does it also not work after force reload of the files app?`

No the problem is the same after scanning the app files. You get an error in the Chrome console saying that the ressource is already loaded

`Newly created files can’t be opened “Unable to open file”

Works fine on my test setup here. Anything in the logs about that?`

Removed and reinstall the extension and the problem is gone

**Comment by juliushaertl** [comment]
Looks like all are fixed now.
