### ISSUE TITLE
Can't edit 1 file .docx, you can't edit this document with other people.

### ISSUE THREAD

**Issue by serzee** [nextcloud/officeonline#208]
**Describe the bug**
Sorry, you can't edit this document with other people.
Session ID: .......
**To Reproduce**
1. Go to SMB/CIFS external storage
2. One file (.docx) has trouble with is issue. others working well.

**Expected behavior**
Please help me fix this. 
I restart nextcloud server and Office Online Server. File lock for editing
**Screenshots**
![image](https://user-images.githubusercontent.com/91408465/134798612-fdd75e32-fad5-47c7-bd2d-cc9506aeffd4.png)

**Client details:**
 - OS: Windows 10
 - Browser [ chrome, edge ]
 - Version 
 - Device: windows 10

## Server details

**Operating system: Ubuntu 18.4

**Web server: Apache 2.4

**Database: Mariadb 10.3

**PHP version: 7.3

**Nextcloud version:  22.1.1  

**Version of the officeonline app :  Office Online Integration version: 1.1.1

**Version of Office Online server: Office online server 2019

**Comment by andyxheli** [comment]
@serzee are you still having an issue. I created a  SMB/CIFS external storage, created a document with in the External storage folder and I had no issues editing the file

**Comment by patschi** [comment]
I'd say as there's no response and I've not been able to reproduce this on my setup, I'll close this one for now. As a long time passed and major versions were released since, please create a new issue if issue persists.
