### ISSUE TITLE
We couldn't find the file you wanted. It's possible the file was renamed, moved or deleted.

### ISSUE THREAD

**Issue by theoneandonly-vector** [nextcloud/officeonline#21]
**Describe the bug**
As soon as I try to open a .xlsx or .docx file I get this error from Microsoft Excel / Word Online:
We couldn't find the file you wanted. It's possible the file was renamed, moved or deleted. // Something Went wrong and we couldn't load this content. Refreshing the browser may fix the problem.

**Expected behavior**
Microsoft Excel / Word Online is showing the file.

**Screenshots**
![image](https://user-images.githubusercontent.com/10380051/95313015-e9c0bc00-088f-11eb-911c-85988d1a6b8e.png)

**Client details:**
 - OS: Windows 10 pro 64bit
 - Browser chrome
 - Version 85

## Server details

**Operating system**:Ubuntu

SNAP-Installation (19.03)

**Nextcloud version:**

**Version of the officeonline app**
Excel / Word

**Version of Office Online server**
16.0.10338.20039

<details>
<summary>Logs</summary>
#### Browser log
a) The javascript console log:
[ncchromeconsole.log](https://github.com/nextcloud/officeonline/files/5339942/ncchromeconsole.log)

**Comment by jonasled** [comment]
I get the same Error Message running NC 20 on apache with PHP 7.4

**Comment by jonasled** [comment]
I've debugged a bit more and it looks like you have to enable TLS1.2 in your .net configuration: https://social.technet.microsoft.com/Forums/en-US/327bbdab-1676-4ff6-9282-df4807e4cf96/sp2016-with-office-online-2016?forum=SP2016

**Comment by theoneandonly-vector** [comment]
> I've debugged a bit more and it looks like you have to enable TLS1.2 in your .net configuration: https://social.technet.microsoft.com/Forums/en-US/327bbdab-1676-4ff6-9282-df4807e4cf96/sp2016-with-office-online-2016?forum=SP2016

I just tried this -> doesn't work for me.

**Comment by theoneandonly-vector** [comment]
> I've debugged a bit more and it looks like you have to enable TLS1.2 in your .net configuration: https://social.technet.microsoft.com/Forums/en-US/327bbdab-1676-4ff6-9282-df4807e4cf96/sp2016-with-office-online-2016?forum=SP2016

does it work on your setup?

**Comment by jonasled** [comment]
yes, I've enabled this option and now it works

**Comment by theoneandonly-vector** [comment]
> yes, I've enabled this option and now it works

Do you know if the office online server needs to be available from the client (my client connects from Internet) or only Nextcloud-Server -> Office Online Server.

Also you just did the registry settings right?

**Comment by jonasled** [comment]
yes, it has to be available from the client and I've done the registry hack. Your office Server needs also a valid SSL cert if you have enabled https on your nextcloud.

**Comment by jonasled** [comment]
You can also check if the browser console or the office Server logs show more details.

**Comment by theoneandonly-vector** [comment]
I have let's Encrypt on both hosts and office-online serve ris available through https from the internet now.
I get this on my console in chrome:

GET https://nc.domain.tld/ocs/v2.php/apps/text/workspace?path=%2FDocname 404 (Not Found)

**Comment by andyxheli** [comment]
https://help.nextcloud.com/t/office-online-error-message-something-went-wrong/100447/11

**Comment by andyxheli** [comment]
1. Save the below text as enable-tls1-2.reg and import it into the server.

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\.NETFramework\v4.0.30319]
"SchUseStrongCrypto"=dword:00000001
```

2. The next step is to disable down level protocols. Again, save the below text as force-tls1-2.reg and import it into each OOS server.


```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols]

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\PCT 1.0]
@="DefaultValue"

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\PCT 1.0\Server]
@="DefaultValue"
"Enabled"=dword:00000000

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0]
@="DefaultValue"

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 2.0\Server]
@="DefaultValue"
"Enabled"=dword:00000000

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0]
@="DefaultValue"

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\SSL 3.0\Server]
@="DefaultValue"
"Enabled"=dword:00000000

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0]
@="DefaultValue"

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.0\Server]
@="DefaultValue"
"Enabled"=dword:00000000

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1]
@="DefaultValue"

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.1\Server]
@="DefaultValue"
"Enabled"=dword:00000000
```

3. Lunch PowerShell as admin
4. iisreset 
5. Test

For more info you can read this post via the url https://social.technet.microsoft.com/Forums/en-US/327bbdab-1676-4ff6-9282-df4807e4cf96/sp2016-with-office-online-2016?forum=SP2016

I tested this today on my setup and it works.

**Comment by andyxheli** [comment]
@theoneandonly-vector this dose seem to be a issue on the officeonline app more on the server side. I was able to fix this issue via above comments. Please confirm that its working for you. If so, can you please close this ticket ?

**Comment by andyxheli** [comment]
I think so too. We can close this. I setup a new Office Online server and had no issues.

**Comment by theoneandonly-vector** [comment]
yes, that's it. sorry for keeping this open.

**Comment by filimonic** [comment]
Worked `"SchUseStrongCrypto"=dword:00000001`, thanks
