### ISSUE TITLE
Web consle error

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/officeonline#237]
Please see below image this happens every time i open up a document 
![21-12-03 22-15-54 6065](https://user-images.githubusercontent.com/59488153/144696657-8700430f-b76e-432d-a352-de226dd7181f.jpg)

Operating system:
Ubuntu 20.04
Web server:
Apache
Database:
MariaDB 10.5.13
PHP version:
8.0.13
Nextcloud version:
23.0.0
Version of the officeonline app
1.1.1
Version of Office Online server
2019

**Comment by juliushaertl** [comment]
The error message is reported by the office online server URL which is loaded inside of an iframe for editing, so there is nothing we can do about that in the app
