### ISSUE TITLE
Enable PHP8.0 Support

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/officeonline#240]
No sure if PHP8.0 is supported.

**Comment by SteelPC** [comment]
I've been running it on php8.0 for more than a month without any issues si far.

**Comment by andyxheli** [comment]
Currently i am running on PHP 8.0 and im not seeing any issues.

**Comment by andyxheli** [comment]
@azul I seen you worked on php7.4 anyway we can add php8.0 since now a lot of users are moving to it.

**Comment by azul** [comment]
Yes. I'm mostly using 7.4 because that's the dev setup i currently have. I'd be happy to see 8.0 added and migrate my dev env to that.

**Comment by andyxheli** [comment]
@azul Thank you so much! I'm sorry to bother you. Right now i use 8.0 on my setup from what i can see its working but again im not a dev so i dont know :)

**Comment by juliushaertl** [comment]
Are you referring to the CI pipeline? The app should work just fine with PHP 8.0.
