### ISSUE TITLE
always connecting to internal ip

### ISSUE THREAD

**Issue by epiphany11** [nextcloud/officeonline#284]
Hi,
i am trying to set up office online app. The Office Onlline Server is answering on /hosting/discovery. In nextcloud the url is configured and it says "server is reachable". Now i am trying to open a word document, it is loading but the browser says "connecting with 10.xxx.xxx.xxx". it shows the internal ip of OOS.
Does anybody knows why? The internal and external ip in office online server is set to the external domain.

THX

**Comment by andyxheli** [comment]
Hello, 

is this how your settings are configured ? 

![image](https://user-images.githubusercontent.com/59488153/161605352-7ad0a745-edaf-49e7-975b-ee84a18512cf.png)

**Comment by andyxheli** [comment]
Also, 

How did you configure your Office Online server? Please see below 


New-OfficeWebAppsFarm -InternalUrl "https://server.contoso.com" -ExternalUrl "https://wacweb01.contoso.com" -CertificateName "OfficeWebApps Certificate" -EditingEnabled

**Comment by epiphany11** [comment]
Hi,
yes i did it like this.
The problem was, that the oos server was  port forwarded via proxy server. Now it has it's own public ip, and it worked.

Thanks for your help

**Comment by andyxheli** [comment]
You're Welcome! Glad you got it figured out. Can you please close out the ticket ?
