### ISSUE TITLE
Erro when opening existing Files with Officeonline

### ISSUE THREAD

**Issue by rgl1234** [nextcloud/officeonline#294]
We are working with NC 21.0.9 and are facing the following Issue with OfficeOnline-App V1.1.3:

All our files are stored on external CIFS-storage.

We can normally creaty new files inside NC with OfficeOnline and work on them. But when we try to open a file that is stored on external-storage that has not been created inside nextcloud, we always get the following error-message:

![image](https://user-images.githubusercontent.com/11720329/162633822-bd88f316-b3cd-4325-b2d4-8ff56b5edad6.png)

In the log-file we always can see the following messages:

![image](https://user-images.githubusercontent.com/11720329/162634278-9219acab-57bb-45df-9a40-759132a19c6a.png)

I think that the problem could be somehow related to the location, where the file is stored. I usually can solve the problem by copiing the file into another location inside NC and then open it from there. Then after copying it back to original location it can normaly also be opened correctly....

Do you have an idea where the problem could come from?

Thanks
rgl

**Comment by patschi** [comment]
It might be indeed related to some locking issues via CIFS. Is this issue still present on the latest versions of NC and OOS?

**Comment by rgl1234** [comment]
Hello @patschi 
Thanks for your feedback. I cannot reproduce the problem in the latest versions....so in the meantime problem might have ben fixed somehow....

**Comment by patschi** [comment]
Great to hear! Closing the issue then.
