### ISSUE TITLE
Nextcloud Office 6.1.0 - Missing Menu -File, edit, ..., close(x)

### ISSUE THREAD

**Issue by Uwe-MrT** [nextcloud/officeonline#303]
**Describe the bug**

In my Nextcloud i open a Document with Nextcloud office 6.0.0
On the Top there is a Menu
File... Edit... etc and X for close

In Nextcloud Office 6.1.0 the Menu is missing.
I can not close the Document.

Go back to Nextcloud Office 6.0.0, the Menu is there.
NC 24.0.0.
Debian 11
PHP 8.0
mysql 10.5.15

**To Reproduce**
Update Nextcloud Office 6.0.0 to Nextcloud Office 6.1.0 and restart all services (reboot linux)

**Client details:**
Client win 10
browser firefox + google chrome

## Server details

**Operating system**:
Debian 11
**Web server:**
Apache 2
**Database:**
Mysql
**PHP version:**
8.0.18
**Nextcloud version:**
24.0.0
**Version of the officeonline app**
6.1.0
**Version of Office Online server**
Collabora Online - Built-in CODE Server	21.11.402	

<details>
<summary>Logs</summary>

</details>

**Comment by andyxheli** [comment]
@Uwe-MrT I think your in the wrong place Office Online only has these versions

![image](https://user-images.githubusercontent.com/59488153/185186467-d5fa8efa-150a-4746-9b7b-fe53b5922c31.png)

**Comment by andyxheli** [comment]
@juliushaertl Can we close this since this user is using the onlineoffice app with collabora server ?

**Comment by juliushaertl** [comment]
Yes,  please try to upgrade to the latest release and report the issue at https://github.com/nextcloud/richdocuments if it still occurs.

**Comment by Uwe-MrT** [comment]
Please close
