### ISSUE TITLE
office online - after update nextcloud excel tabs not avilable

### ISSUE THREAD

**Issue by rlu01** [nextcloud/officeonline#306]
**Describe the bug**

**To Reproduce**
1. Go to 'nextcloud 24.0.1 excel document'
2. Click on 'excel an open on office online'
3. Scroll down to 'no tabs on excel sheet avilable'

**Expected behavior**
we have upgraded our nextcloud instance to version 24.0.1. now we have the problem that in office online the tabs of the excel documents are no longer displayed. do you have any information about this or how can we delete the problem.

**Screenshots**

**Client details:**
 - Browser [all]
 - Device: [e.g. iPhone6, desktop]

## Server details

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:*24.0.1*

**Version of the officeonline app*1.1.3*

**Version of Office Online server*16.0.10379.20000*

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by TheACF** [comment]
Same Issue at my installation after upgrading to nc24.0.1

**Comment by madmax66rus** [comment]
same issue after upgrading to nc24. oos ver.16.0.10385.20001.
there is a empty line appears at top of opened excel file and it prevent showing bottom line of excel online editor.
workaround - disable office online integration plugin and install wopi plugin instead.
works same, but documents opens in new tab.

**Comment by BenjaminNVS** [comment]
Same here with NextCloud  24.0.1.
WOPI don't do the trick. Our Nextcloud can't see the OOS.

**Comment by rlu01** [comment]
> My decision:
> 
> Install Custom CSS Plugin go: /settings/admin/theming In the settings, add a style that fixes the error:
> 
> #officeonline-wrapper { top: 0 !important; }

that was very helpful problem solved thank you

**Comment by rlu01** [comment]
thx at all
