### ISSUE TITLE
Error - Failed to open the requested file.

### ISSUE THREAD

**Issue by exander77** [nextcloud/officeonline#308]
Opening files causes:
```

Error

    Failed to open the requested file.

```

**Comment by denhomyakov** [comment]
I have error too.
![Error](https://user-images.githubusercontent.com/72086909/175504443-da22815e-c21a-4fa6-9be2-cba58c8723e4.JPG)

This is config
PS C:\Users\administrator> Set-OfficeWebAppsFarm -OpenFromUrlEnabled:$true


FarmOU                                       :
InternalURL                                  : http://office.mydomen.com/
ExternalURL                                  :
AllowHTTP                                    : True
AllowOutboundHttp                            : False
SSLOffloaded                                 : False
CertificateName                              :
S2SCertificateName                           :
EditingEnabled                               : True
LogLocation                                  : C:\ProgramData\Microsoft\OfficeWebApps\Data\Logs\ULS
LogRetentionInDays                           : 7
LogVerbosity                                 :
Proxy                                        :
CacheLocation                                : C:\ProgramData\Microsoft\OfficeWebApps\Working\d
MaxMemoryCacheSizeInMB                       : 75
DocumentInfoCacheSize                        : 5000
CacheSizeInGB                                : 15
ClipartEnabled                               : False
OnlinePictureEnabled                         : False
OnlineVideoEnabled                           : False
TranslationEnabled                           : False
MaxTranslationCharacterCount                 : 125000
TranslationServiceAppId                      :
TranslationServiceAddress                    :
RenderingLocalCacheLocation                  : C:\ProgramData\Microsoft\OfficeWebApps\Working\waccache
RecycleActiveProcessCount                    : 5
AllowCEIP                                    : False
OfficeAddinEnabled                           : False
ExcelRequestDurationMax                      : 300
ExcelSessionTimeout                          : 450
ExcelWorkbookSizeMax                         : 30
ExcelPrivateBytesMax                         : -1
ExcelConnectionLifetime                      : 1800
ExcelExternalDataCacheLifetime               : 300
ExcelAllowExternalData                       : True
ExcelUseEffectiveUserName                    : False
ExcelWarnOnDataRefresh                       : True
ExcelUdfsAllowed                             : False
ExcelMemoryCacheThreshold                    : 85
ExcelUnusedObjectAgeMax                      : -1
ExcelCachingUnusedFiles                      : True
ExcelAbortOnRefreshOnOpenFail                : True
ExcelEnableCrossForestKerberosAuthentication : False
ExcelAutomaticVolatileFunctionCacheLifeTime  : 300
ExcelConcurrentDataRequestsPerSessionMax     : 5
ExcelDefaultWorkbookCalcMode                 : File
ExcelRestExternalDataEnabled                 : True
ExcelChartAndImageSizeMax                    : 1
OpenFromUrlEnabled                           : True
OpenFromUncEnabled                           : True
OpenFromUrlThrottlingEnabled                 : True
PicturePasteDisabled                         : True
RemovePersonalInformationFromLogs            : False
AllowHttpSecureStoreConnections              : False
Machines                                     : {MSK-OFFICE-SRV}



PS C:\Users\administrator> New-OfficeWebAppsHost -domain "nextcloud.mydomen.com"

allowList
---------
{nextcloud.mydomen.com}


PS C:\Users\administrator> Get-OfficeWebAppsHost

allowList
---------
{nextcloud.mydomen.com}

**Comment by denhomyakov** [comment]
![Error2](https://user-images.githubusercontent.com/72086909/175505653-529b76d6-a28b-4dc4-9735-4e5bbbf743dd.JPG)

**Comment by exander77** [comment]
It is caused by disabling legacy encryption, even tough test said the legacy encryption is no longer needed.

**Comment by juliushaertl** [comment]
Before todays release only external urls were supported. Now with the latest 1.1.4 release your existing OfficeWebAppsFarm configuration with only an internal url should also match.

Can you check that with the latest release?

Reference in code https://github.com/nextcloud/officeonline/blob/master/lib/WOPI/Parser.php#L178-L183

**Comment by patschi** [comment]
There were changes implemented by Julius, however no response if issues still present in over half a year - hence suspecting this issue has been fixed. Closing this.
