### ISSUE TITLE
Installation of app fails with exception

### ISSUE THREAD

**Issue by happyhappahappsie** [nextcloud/officeonline#34]
An exception occurred while executing 'CREATE UNIQUE INDEX rd_wopi_token_idx ON oc_officeonline_wopi (token)': SQLSTATE[42P07]: Duplicate table: 7 ERROR: relation "rd_wopi_token_idx" already exists

Nextcloud 18.0.10

**Comment by soundcatchers** [comment]
I have the same issue... An exception occurred while executing 'CREATE UNIQUE INDEX rd_wopi_token_idx ON oc_officeonline_wopi (token)': SQLSTATE[42P07]: Duplicate table: 7 ERROR: relation "rd_wopi_token_idx" already exists

Trying to get online office document editing working through nextcloud. I enabled and disabled several packages including this app and then discovered that this might be the way to go as I found a recent article on it. But when I went to re-enable to app the above error is now displayed and I am unable to reinstall the app.

Nextcloud 19.0.1
Operating System: | Linux 4.14.141-169 armv7l
CPU: | ARMv7 Processor rev 3 (v7l) (8 cores)

**Comment by andyxheli** [comment]
@happyhappahappsie is this still on issue on NC23 ? If not, can you please close this issue?

**Comment by andyxheli** [comment]
dup of https://github.com/nextcloud/officeonline/issues/99

**Comment by juliushaertl** [comment]
Let's close this since this issue should not occur with the latest release. Let us you if you still encounter this.
