### ISSUE TITLE
Failed to open the requested file

### ISSUE THREAD

**Issue by perkinF** [nextcloud/officeonline#346]
**Describe the bug**
When I open any document with office online in nextcloud, nextcloud reports an error "failed to open the requested file"

**To Reproduce**

**Expected behavior**
When I open any document with office online in nextcloud, nextcloud reports an error "failed to open the requested file"

**Screenshots**
![image](https://user-images.githubusercontent.com/108869959/186312016-c24a7b3d-cedf-47e5-9b16-2fe5d30d4b1f.png)
![image](https://user-images.githubusercontent.com/108869959/186312153-1037db2a-bf16-42c1-8103-4333f225f0f7.png)
![image](https://user-images.githubusercontent.com/108869959/186312201-fd349026-3b3c-441c-bbe8-3179c3fc57aa.png)

**Client details:**
 - Browser  chrome, safari
 - Device: [e.g. iPhone6, desktop]

## Server details

**Operating system**: ubuntu server LTS 22.04

**Web server:

**Database:**

**PHP version:**
PHP 8.0

**Nextcloud version:**
nextcloud 24.0.0

**Version of the officeonline app**
1.1.3

**Version of Office Online server**
office online server 2016

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
![image](https://user-images.githubusercontent.com/108869959/186312423-1500141f-9b41-4e80-862c-56a84901c467.png)

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by andyxheli** [comment]
@perkinF try the following 

https://help.nextcloud.com/t/office-online-error-message-something-went-wrong/100447/11?u=andyxheli

**Comment by ScionOfDesign** [comment]
Disabling the built-in "Nextcloud Office" app (which uses Collabra) worked for me.

**Comment by patschi** [comment]
There was no reply if following steps suggested by @AndyXheli fixed the issue for almost a year, hence closing this down as stale.
