### ISSUE TITLE
Support for NC 24 & 25

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/officeonline#349]
Currently app dose not launch from the NC 25 dashboard same as NC 24

![image](https://user-images.githubusercontent.com/59488153/188192435-57a887d5-69c3-4192-b182-ee65347caa6c.png)

**Comment by juliushaertl** [comment]
Thanks, I'll have a look at that before the final release of 25.

**Comment by andyxheli** [comment]
You're Welcome! Same issue for NC 24 #299

**Comment by andyxheli** [comment]
Hey @juliushaertl sorry to bug you i know your busy. Any updates on this ?

**Comment by Zupe007** [comment]
@juliushaertl Hi, do you have an approximate time window when you will deploy the app?
After updating to Nextcloud 25 we are not able to create files and launch the app.

**Comment by technikfrek** [comment]
I have the same problem, as described by @AlexanderZuehr .
Is there any progress?
Thanks!

**Comment by juliushaertl** [comment]
I just released a new version (1.1.4) including compatibility for 24/25.
