### ISSUE TITLE
I cannot see other users actively writing in the same document

### ISSUE THREAD

**Issue by theoneandonly-vector** [nextcloud/officeonline#350]
**Describe the bug**
I cannot see other users actively writing in the same document. To see their changes I need to write somehting on my own in the doc but I don't see them typing or who is it (especially if there are multiple editors I don't know with who to speak). AND the editors who opened the file are listed as current editors, but they will be kept there even if they close the document and they also are listed multiple times if they reopen the doc so it can happen that I see the same editor 10 times..

**To Reproduce**
1. Open a word-document on one user 
2. Open the same doc on another user
3. write as one of the users and check on the other (-> cannot see their live-edits)
4. close the doc on one user (user is still visible in editors)
5. Open the doc anothe rtime (user is visibke two times as an editor in the same doc)

**Expected behavior**
I can see live edits of other editors.
an editor can only be shown once in the list of editors.
an editor will be remove form the list of curren teditors after he closes the doc.

**Client details:**
 - OS: Windows 11
 - Browser chrome
 - Version Version 105.0.5195.52 64bit
 - Device: Desktop

## Server details

**Operating system**:
Ubuntu 22.04

**Web server:**
Apacher (Nextcloud is installed as a snap)

**Database:**
mysql
Version: 8.0.30

**PHP version:**
8.0.21

**Nextcloud version:**
22.2.0.2

**Version of the officeonline app**
1.1.3	

**Version of Office Online server**
16.0.10338.20039

**Comment by theoneandonly-vector** [comment]
after some time the other editors will be removed form the list. but still the main problem I have is that I don't see the others editing live (there should be a color for each editors shwoing what he is doing live)

**Comment by ne0YT** [comment]
@andyxheli can you create a vid/gif?

**Comment by andyxheli** [comment]
Here you go. I do notice a big time lag 

https://user-images.githubusercontent.com/59488153/197228002-3ed8d6f9-4b92-4591-9bb6-51962e8e9711.mp4

**Comment by juliushaertl** [comment]
I don't see any reason why the integration would cause that. It looks a bit like office is pausing the sync while you don't have focus on the browser window.

**Comment by andyxheli** [comment]
Let me do a check with two computers same users and report back

**Comment by andyxheli** [comment]
@juliushaertl I check with two different computes user 1 was on pc 1 users 2 was on pc2 and i was focused on the browser and still still a big delay im not sure if that's a OOS thing or not

**Comment by theoneandonly-vector** [comment]
idk why.. but its not happening since I re-run the deployment command to create the office online server (on the same already running server)
