### ISSUE TITLE
Remove the black Bar on top to make better use of the Display

### ISSUE THREAD

**Issue by theoneandonly-vector** [nextcloud/officeonline#352]
**Is your feature request related to a problem? Please describe.**
I would like to have the red marked space removed so I can use more of my Display to edit files

![image](https://user-images.githubusercontent.com/10380051/189080816-1ff20653-9ce0-45c4-b41a-c98d638b2c6d.png)

**Comment by thiblcr** [comment]
Excellent idea, I was going to make the same suggestion.

**Comment by thiblcr** [comment]
Here is a little trick to improve that:
https://github.com/nextcloud/officeonline/issues/313

It seems to be a Nextcloud24 related issue.

**Comment by ne0YT** [comment]
this workaround works, but it should be fixed

**Comment by juliushaertl** [comment]
Duplicate of #313, fix is in #370
