### ISSUE TITLE
Office 365 integration

### ISSUE THREAD

**Issue by ramiuslr** [nextcloud/officeonline#369]
Is it planned to make this plugin compatible with Office 365 account ?
I mean instead of the OP OfficeOnlineServer url, indicate in the settings the url of a O365 account.
I'm not very familiar with MS Office, so I have no idea if it could be possible.

Thank you for your great work !

**Comment by andyxheli** [comment]
Curently on owncloud 

https://doc.owncloud.com/server/next/admin_manual/enterprise/collaboration/msoffice-wopi-integration.html

**Comment by thiblcr** [comment]
Ok, thank you, I will give it a try !

**Comment by juliushaertl** [comment]
Office 365 needs storage providers to become part of the [cloud storage partner program](https://developer.microsoft.com/en-us/office/cloud-storage-partner-program#Signup). With a on-premise solution we do not fit into the criteria from there:

> The CSPP is for companies that store files in their cloud for third parties and want to add online editing for their customer's Microsoft Excel, Word and PowerPoint files stored in the company's cloud offering.  To be considered for this program, your CSPP solution must meet the following minimum requirements:

> 1. Be a proprietary cloud storage environment owned wholly by the partner company

ownCloud seems to work around this by registering a proxy service, but that means that all opened documents also go through their proxy servers and their solution doesn't seem to be available as free software (and only be available for customers).

**Comment by smehrens** [comment]
with https://apps.nextcloud.com/apps/files_external_onedrive
it would be possible to copy the file for editing to onedrive, open it in office365, save it and move it back to nextcloud.
dont know how long this would take as an automated process, but it would enable file acces for all "azure only applications".

sure all files would be saved in onedrive for a short time, but with wopi access ms would have access anyway.

same should be able with https://apps.nextcloud.com/apps/files_external_gdrive and google apps.

**Comment by andbag** [comment]
Given Nextcloud's fair use policy, enterprise customers who manage more than 500 users are already required to purchase licenses for the notification service. With this in mind, it would make sense to consider developing a solution similar to Owncloud's approach for integration with Office 365 that is specifically tailored to this customer segment and offered as a paid feature. Large public institutions in particular are looking for a compromise between user acceptance and strict data protection standards. There is also an urgent need for an exit strategy for Office 365, especially in the event that the Data Privacy Framework is declared invalid. I am sure that these institutions would be very willing to invest in this solution. Have other major customers already requested this feature?
