### ISSUE TITLE
Bottom Status Bar Missing 

### ISSUE THREAD

**Issue by schoasch10** [nextcloud/officeonline#375]
In Nextcloud Hub Versions 24 and 25 when opening office documents the bottom status bar is missing (word, excel).
Especially in Excel it´s not possible anymore to select the different sheets at the bottom bar.
![bottom-bar1](https://user-images.githubusercontent.com/65654186/197384056-523f324e-df5b-4ec7-bb1e-a696b687fc41.png)

**Comment by andyxheli** [comment]
should be fixed by https://github.com/nextcloud/officeonline/pull/370
