### ISSUE TITLE
Other users (10) also work with this file

### ISSUE THREAD

**Issue by ihard** [nextcloud/officeonline#397]
**Describe the bug**
Incorrect display of the number of users who edit the file.

**To Reproduce**
1. Open document
2. Close document
3. Open document
4. Close document
5. The list of users editing the file will have duplicate entries with the same person's name as many times as the document has been opened and closed. 

**Expected behavior**
No duplicate entries

**Client details:**
 - OS: MacOS
 - Browser Safari 16.3,  Chrome 109
 - Device: Macbook

## Server details

Docker image nextcloud:25.0.3

**Operating system**:
Ubuntu 20.04

**Web server:**

Nginx

**Database:**

Postgres

**Nextcloud version:**

25.0.3

**Version of the officeonline app**

1.14

**Version of Office Online server**

16.0.10338.20039

**Comment by juliushaertl** [comment]
This looks like a specific issue with Chrome where the Office Online server is not getting aware of the lost connection. Looking at the thread from https://social.msdn.microsoft.com/Forums/office/en-US/1b783d1c-c686-4b2d-b23f-4977e6bed806/wopi-unlock-call-never-gets-triggered-in-chrome-and-latest-edge-browser?forum=os_office I don't consider this an issue with the Nextcloud app itself.
