### ISSUE TITLE
Interface of configurationmenu not loading correctly

### ISSUE THREAD

**Issue by aignerat** [nextcloud/officeonline#4]
**Describe the bug**
I see a blank screen on the app, the HTML-Code ist:
<div id="app-content">
--
  | <div id="admin-vue" data-initial="{&quot;wopi_url&quot;:&quot;&quot;,&quot;edit_groups&quot;:&quot;&quot;,&quot;use_groups&quot;:&quot;&quot;,&quot;doc_format&quot;:&quot;ooxml&quot;,&quot;external_apps&quot;:&quot;&quot;,&quot;canonical_webroot&quot;:&quot;&quot;,&quot;disable_certificate_verification&quot;:false,&quot;templatesAvailable&quot;:false,&quot;settings&quot;:{&quot;enabled&quot;:true,&quot;installed_version&quot;:&quot;1.0.0&quot;,&quot;types&quot;:&quot;filesystem,dav,prevent_group_restriction&quot;}}"></div>
  | </div>

**To Reproduce**
1. Go to Settings
2. Click on Office Online

**Expected behavior**
See the settings for online office configruation.

**Client details:**
 - OS: Windows 10
 - Browser Chrome / Edge 
 - Version 85.0.4183.102 / Version 85.0.564.51
 - Device: Webinterface

## Server details

**Operating system**: Centos 7

**Web server:** Apache

**Database:** Postgres 9.6

**PHP version:** PHP 7.2.32

**Nextcloud version:** 19.0.1

**Version of the officeonline app** 1.0.0

**Version of Collabora Online** n/a

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
none

#### Browser log
```
Insert your browser log here, this could for example include:

a) Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-abcdef'), or a nonce ('nonce-...') is required to enable inline execution. officeonline:24

</details>

**Comment by juliushaertl** [comment]
> Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-abcdef'), or a nonce ('nonce-...') is required to enable inline execution. officeonline:24

That seems odd, could you check the linked source where that is originating from?

**Comment by aignerat** [comment]
was a problem on my side, sry for the confusion
