### ISSUE TITLE
Office-Online Share Dropdown Broken

### ISSUE THREAD

**Issue by AlexanderZuehr** [nextcloud/officeonline#406]
**Describe the bug**
Hey @juliushaertl it seems the new update of nextcloud partly broke the feature to share a office-online document with other users from inside of office-online. You can write a username with whom you want to share the document but the dropdown feature isnt showing any users of the nextcloud. You can still share the file if you write down the name of an other user and press "Enter", it seems to pick an invisible user.

If you are trying to share the file from your nextcloud files the dropdown and suggestions are working.

The users are integrated into nextcloud via ldap.

I've made 2 screenshots to better show my problem. The administrator is a representative example.

Here you can see it working from the Nextcloud Files.
<img width="1283" alt="Bildschirm­foto 2023-03-01 um 11 19 01" src="https://user-images.githubusercontent.com/76497172/222112845-3ef11c93-728c-4b13-b8f2-4bf2e27d85ee.png">

Here it isnt working from within of Office-Online.
<img width="1597" alt="Bildschirm­foto 2023-03-01 um 11 19 46" src="https://user-images.githubusercontent.com/76497172/222112851-666edcd8-afbf-42d8-9d27-9cb3b0f06ca7.png">

**Comment by juliushaertl** [comment]
This looks like a server bug, I'm not sure about which version you run but https://github.com/nextcloud/server/pull/36998 could address this.

**Comment by AlexanderZuehr** [comment]
> This looks like a server bug, I'm not sure about which version you run but [nextcloud/server#36998](https://github.com/nextcloud/server/pull/36998) could address this.

Am i reading it correctly, that this fix is backported to nextcloud 25 and will be usable in the next days/weeks?

**Comment by juliushaertl** [comment]
Not yet, but I've asked in the PR. Release would be with the next maintenance release once the backport was merged.

https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Comment by AlexanderZuehr** [comment]
Fixed with Nextcloud Update 25.0.5
