### ISSUE TITLE
Office online does not respect a local locked file by user.

### ISSUE THREAD

**Issue by small1** [nextcloud/officeonline#428]
**Describe the bug**
Open a document for local edit.  The document gets locked in the web interface.  Another user can see that it is locked. 

BUT if the user click on it office online opens the document and the user can write in it and changes is save. Not respecting the lock at all. 

If this is done in nextcloud office a popup says that the document is locked and opened in read only mode.  

**To Reproduce**
1. Open file for local edit
2. See that it gets locked
3. Other user that has write permission opens the file
4. writes text and the file gets saved regardless if it is locked for local edit or not.

**Expected behavior**
office online should say that the docment is locked and opened in read only mode

**Screenshots**

**Client details:**
 - OS: linux and windows
 - Browser: chrome and firefox
 - Version: latest stable
 - Device: Desktop and laptop

## Server details

**Operating system**: ubuntu 22.04

**Web server:** apache

**Database:** mysql

**PHP version:** 8.1

**Nextcloud version:** 26.0.0

**Version of the officeonline app** 2.0.1

**Version of Office Online server** 16.0.10396.20000

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Nothing relevant found
```

#### Browser log
```
Nothing relevant found 

c) ...
```

</details>

**Comment by enoch85** [comment]
Tested on both Firefox and Chrome:

1. User A: Create a new Word file online/locally ( tested online)
2. User A: Write something in that file from the online editor and close it
3. User A: Share the file with User B
4. User A: Open it locally
5. User B: Hit F5 online and notice it's locked by User A
6. User A: Write something in your local document and hit save
7. User A: Notice that the file is now saved locally and synced to Nextcloud (keep the document open locally)
8. User B: Open it online and write something
9. User B: GCan edit the file, and the changes are saved
10. User A: still has the document open locally, but now the desktop sync client gets errors regarding that the file can't be synced
11. User B: Closes the document
12. User A: Closes local edit ad opens the document - the changes that User B made are present
12.5. Even if User B would close and open the document while it's open locally by User A - the changes would still be present.

**Comment by juliushaertl** [comment]
I've pushed a fix to https://github.com/nextcloud/officeonline/pull/442 but could only partly validate it due to issues with my OSS setup as outlined in the PR. Any help in testing is very welcome.
