### ISSUE TITLE
Viewer for visio files

### ISSUE THREAD

**Issue by mleikin-gh** [nextcloud/officeonline#433]
Good morning,
Is there any possibility to be able to manage Microsoft Visio files with with officeonline ?
Greetings,
Miguel Angel Leikin

**Comment by patschi** [comment]
Unfortunately doesn't look like: OOS only supports Word, PowerPoint, Excel and OneNote as per [Microsoft docs](https://learn.microsoft.com/en-us/officeonlineserver/office-online-server-overview). Visio would require SharePoint integration from what I looks like.

As this app is for OOS, closing down this issue (sorry!)
