### ISSUE TITLE
Check why saving might not be triggered immediately after close

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/officeonline#45]
As reported by @wiswedel it seems there is some delay in saving the document.

**Comment by Shen** [comment]
I can confirm the error (NC 20.0.4). When I open a document in OnlyOffice, edit it and close it again via the X, the last change is not displayed. Also, the old file is downloaded when I click on Download. After a manual page reload, the last change is displayed and the current file is downloaded when I click Download.

**Comment by juliushaertl** [comment]
This is not about ONLYOFFICE but Microsoft Office Online, for ONLYOFFICE please report to https://github.com/ONLYOFFICE/onlyoffice-nextcloud/

**Comment by juliushaertl** [comment]
Could never reproduce that so closing for now.
