### ISSUE TITLE
Co-authoring is not working in word documents with macros

### ISSUE THREAD

**Issue by justkrevedko** [nextcloud/officeonline#459]
**Steps to reproduce the behavior:**
1. Share .docm file with another user
2. Open file by yourself - it works fine, opens in edit mode
3. Another user tryes to open same file - error message "Unfortunately, you can't edit this file with another user" and button to open in read mode

**Expected behavior**
Open in edit mode

**Screenshots**
![image](https://github.com/nextcloud/officeonline/assets/175383/3a64193d-23e5-4b0a-87bd-86e3b6f1e578)

**Client details:**
 - OS: Windows 10
 - Browser: last version MS Edge or Firefox

## Server details
**Operating system**:
Ubuntu 22.04
**Web server:**
nginx
**Database:**
postgresql
**PHP version:**
8.1
**Nextcloud version:**
26.0.2
**Version of the officeonline app**
2.0.2
**Version of Office Online server**
2019 (16.0.10374.20000)

**Comment by juliushaertl** [comment]
According to https://answers.microsoft.com/en-us/msoffice/forum/all/not-able-collaborate-files-with-macros-in-office/e435c330-933e-4b55-be65-163e4ac1ffcf this is a limitation of office itself.
