### ISSUE TITLE
Excel not working because CORS Policy

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/officeonline#478]
**Describe the bug**

**To Reproduce**
1. Open an excel file

**Expected behavior**
Excel file should open but a CORS Policy is blocking. All other files working.
If I create a link on my new OOS Server O can open all excel files. In NextCloud it is not working (Nextcloud 27.0.2 with PHP 8.2).
Word or PowerPoint is working fine in NextCloud, no problems here.

**Screenshots**
![image](https://github.com/nextcloud/officeonline/assets/1473674/914ce748-ed87-4e28-ad5a-a68e8b0eb6fe)

## Server details

**Operating system**:
Ubuntu 20.04

**Web server:**
Apache 2.4

**Database:**
MariaDB 10.6

**PHP version:**
8.2

**Nextcloud version:**
27.0.2

**Version of the officeonline app**
2.0.2

**Version of Office Online server**
OOS 2019

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Empty no errors
```

#### Browser log
```
See screenshot please
```

</details>

**Comment by juliushaertl** [comment]
We don't have any specific policy for that defined in the app. Can you share the full output of the js console? From the visible errors it looks like that seems an error related more to the Office Online server itself then to our app.

**Comment by Dennis1993** [comment]
Hey,
thanks for your quick response!
I‘ve tested some things. We have two Online Office Servers in a cluster with a load balancer. I removed one server from the cluster and load balancer. Now I configured the Nextcloud with the single server, now it works.
So I think it is a problem on this site and not Nextcloud ☺️

**Comment by juliushaertl** [comment]
Thanks for the update, glad to hear that :)
