### ISSUE TITLE
Ready for NextCloud 28?

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/officeonline#503]
Is this app ready for NextCloud 28?
In the store is no version for 28 available and I want to update my servers because we need the new performance optimizations :)

Thanks!

**Comment by eddiermar** [comment]
Please support NC 28!

**Comment by themkarimi** [comment]
I have also had my nextcloud instance updated to version 28 and office online integration is no longer working!

**Comment by Dennis1993** [comment]
@juliushaertl is fixing that at the moment so I think this post is solved ☺️
THANK YOU VERY MUCH! 👍

https://github.com/nextcloud/officeonline/pull/490#event-11293896394

**Comment by juliushaertl** [comment]
Yes, there is still some testing needed but I'll probably publish a new release the next few days

**Comment by Dennis1993** [comment]
Any progress here? :)
Many users can‘t upgrade to 28 :(

**Comment by Dennis1993** [comment]
😢

**Comment by Dennis1993** [comment]
> Yes, there is still some testing needed but I'll probably publish a new release the next few days

@juliushaertl 
Can you give me a little information about whether the app is being further developed?
I would like to update to the 28 but it doesn't work without the app.
Thank you! :)
