### ISSUE TITLE
2.1.0 on nextcloud 28.0.2 creation menu not in local language

### ISSUE THREAD

**Issue by SteelPC** [nextcloud/officeonline#522]
The main button "+ New file" for file creation is not in the local language anymore but defaults to english

![Screenshot 2024-02-18 at 17-31-31](https://github.com/nextcloud/officeonline/assets/71431903/183a054f-e8f4-4932-b482-546073ba883d)

**Comment by Orchal** [comment]
Hi,

I found that in lib/AppInfo/Application.php, the text is : New document, New spreadsheet and New presentation.
In l10n files, it's New Document, New Spreadsheet and New Presentation, with uppercase on the second word.

I changed that in Application.php and now it's translated.

**Comment by Orchal** [comment]
Hi,

I noticed that in Application.php, when new files are registered, the app is richdocuments. Maybe this is intended, I just wanted to bring that up in case of a copy paste not adapted.

**Comment by Dennis1993** [comment]
Thank you very much, I created a pull request for you and your fix. :)
