### ISSUE TITLE
officeonline 2.1.0 does not work with public links on Nextcloud 27.1.6

### ISSUE THREAD

**Issue by it-unit-iiep** [nextcloud/officeonline#530]
**Describe the bug**

**To Reproduce**
1. create a public link for a document such as a docx file
2. open the public link in a browser
3. office online does not open, we can only download the document

**Expected behavior**
Office online should open the document.

**Screenshots**

**Client details:**
 - OS: windows, macos, linux
 - Browser firefox, chrome, edge

## Server details

**Operating system**:  Debian 11

**Web server:**  nginx

**Database:**  postgres

**PHP version:** 8.1

**Nextcloud version:** 27.1.6

**Version of the officeonline app** 2.1.0

**Version of Office Online server** 

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Browser log does not show any errors
```
## Workaround
Downgrading to Office online app to 2.0.3 brings back the expected behavior.
</details>

**Comment by Dennis1993** [comment]
Hey,

thank you for your report!
I think that’s discussed here: https://github.com/nextcloud/officeonline/issues/521

can you try this fix how discribed in the thread and write a short feedback?

Thank you very much! ☺️
