### ISSUE TITLE
I have a problem 

### ISSUE THREAD

**Issue by Alejandroduoc** [nextcloud/officeonline#565]
bootstrap:19 Proxying an event bus of version 3.1.0 with 1.1.4
session-heartbeat.js:103 session heartbeat polling started
Ewa.js?bn=424195637:2 GET https://serverofficeuchile.cl/x/_layouts/app_scripts/Ewa.tmcore.js?bn=424195637 net::ERR_ABORTED 404 (Not Found)
Ewa.js?bn=424195637:2 GET https://serverofficeuchile.cl/x/_layouts/app_scripts/Ewa.tmcore.js?bn=424195637&retries=1 net::ERR_ABORTED 404 (Not Found)
Ewa.js?bn=424195637:2 GET https://serverofficeuchile.cl/x/_layouts/app_scripts/Ewa.tmcore.js?bn=424195637&retries=2 net::ERR_ABORTED 404 (Not Found)

**Comment by fishoflove** [comment]
I have the same problem on my environment. Have you found any solution for this?

**Comment by juliusknorr** [comment]
The scripts are originating from the office online server so there is nothing we can do about that on our integration.

**Comment by SteelPC** [comment]
Late but fixed... go to C:\Program Files\Microsoft Office Web Apps\ExcelServicesWfe\_layouts\App_Scripts make a copy of Ewa.tm.js and rename it Ewa.tmcore.js
