### ISSUE TITLE
Optional parameter $forceIcon declared before required parameter $mode

### ISSUE THREAD

**Issue by koelle25** [nextcloud/officeonline#587]
**Describe the bug**
Following PHP error is logged in _nextcloud.log_:
```
[PHP] Fehler: Optional parameter $forceIcon declared before required parameter $mode is implicitly treated as a required parameter at /var/www/html/custom_apps/officeonline/lib/Controller/TemplatesController.php#196
	GET /csrftoken
	von 10.0.11.4 von kevin.koellmann um 04.09.2024, 10:04:32
```

**To Reproduce**
1. Open a document in Nextcloud web interface, so it gets opened with the Office Online integration
2. Go to 'https://<yourcloud.com>/settings/admin/logging'
3. See error

**Expected behavior**
No error in log.

**Screenshots**
-/-

**Client details:**
 - OS: Windows 11
 - Browser: Firefox
 - Version: 115 ESR
 - Device: Desktop

## Server details

**Operating system**: Ubuntu 22.04

**Web server:** NGINX

**Database:** MariaDB

**PHP version:** 8.2.23

**Nextcloud version:** 29.0.6

**Version of the officeonline app:** 2.2.1

**Version of Office Online server:** 16.0.8471.8525

<details>
<summary>Logs</summary>

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"hVXMJViROkKZxGCYdA2o","level":3,"time":"2024-09-04T10:04:32+02:00","remoteAddr":"10.0.11.4","user":"kevin.koellmann","app":"PHP","method":"GET","url":"/csrftoken","message":"Optional parameter $forceIcon declared before required parameter $mode is implicitly treated as a required parameter at /var/www/html/custom_apps/officeonline/lib/Controller/TemplatesController.php#196","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0","version":"29.0.6.1","data":{"app":"PHP"},"id":"66d8172b1ef2e"}
```

#### Browser log
```

```

</details>

**Comment by IGLADI** [comment]
+1
