### ISSUE TITLE
Add support for NextCloud version 30

### ISSUE THREAD

**Issue by atalakey4work** [nextcloud/officeonline#596]
**Is your feature request related to a problem? Please describe.**
Office online does nit currently work on NextCloud version 30.

**Describe the solution you'd like**
Add support for NextCloud version 30.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by Dennis1993** [comment]
Pull request is closed: https://github.com/nextcloud/officeonline/pull/543

**Comment by atalakey4work** [comment]
@Dennis1993 I'm still unable to install the beta version.

$ occ app:update --allow-unstable -- officeonline
officeonline is up-to-date or no updates could be found

**Comment by Dennis1993** [comment]
This is just a pull request. I don’t know what is to do to create a new release. Maybe @juliusknorr can Tell us more about it ☺️

**Comment by atalakey4work** [comment]
@juliusknorr can you please help with getting this published.

**Comment by atalakey4work** [comment]
@juliusknorr @VicDeo @DeepDiver1975 for your kind support please.

**Comment by Dennis1993** [comment]
Is there any news here? With every release, we just wait for this plugin. No update is possible, as was the case with previous versions. Without any information, it's not so nice. :)

Thanks!

**Comment by Dennis1993** [comment]
I‘ve installed a test server with NC30 and Acrobat the untested app. It‘s working for me.

**Comment by atalakey4work** [comment]
@Dennis1993 can you explain how to Acrobat the untested app?

**Comment by Dennis1993** [comment]
> [@Dennis1993](https://github.com/Dennis1993) can you explain how to Acrobat the untested app?

Update to Nextcloud 30. After that go to Apps and Click on the Button „activate untested App“ now you can activate it.

**Comment by Dennis1993** [comment]
New version was released 😍
Thanks!
