### ISSUE TITLE
PDF Reading Bug

### ISSUE THREAD

**Issue by siimaarmaa** [nextcloud/officeonline#86]
If Nextcloud PDF viewer (Nextcloud Featured module) and Office Online integration are activated, you will receive an error message when opening the PDF.

**Client details:**
 - OS:  Windows 10, 1909
 - Browser: MS Edge (Chrome based), 87.0.664.75
 - Device: laptop

**Server details**
- Operating system: CentOS Linux 8, Linux 4.18.0-193.19.1.el8_2.x86_64
- Web server: Apache/2.4.37 (centos)
- Database: MariaDB, 10.2.32
- PHP version: PHP 7.3.25 (cli) with Zend Engine v3.3.25 and Zend OPcache v7.3.25
- Nextcloud version: 20.0.4
- Version of the officeonline app: 1.0.2
- Version of Office Online server:  Office Online Server, 16

#### Nextcloud log (data/nextcloud.log)
```
[officeonline] Error: OCP\Files\NotFoundException: /*************/files/****************/******************.pdf at <<closure>>

0. /var/www/html/nextcloud/lib/private/Files/Node/Folder.php line 140
   OC\Files\Node\Root->get("/*********** ... f")
1. /var/www/html/nextcloud/apps/officeonline/lib/Controller/DocumentController.php line 228
   OC\Files\Node\Folder->get("/******** ... f")
2. /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 169
   OCA\Officeonline\Controller\DocumentController->index("118758", "/************ ... f")
3. /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Officeonline ... {}, "index")
4. /var/www/html/nextcloud/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Officeonline ... {}, "index")
5. /var/www/html/nextcloud/lib/private/Route/Router.php line 308
   OC\AppFramework\App::main("OCA\\Officeonli ... r", "index", OC\AppFramework\ ... {}, {action: null,_r ... "})
6. /var/www/html/nextcloud/lib/base.php line 1008
   OC\Route\Router->match("/apps/officeonline/index")
7. /var/www/html/nextcloud/index.php line 37
   OC::handleRequest()

GET /index.php/apps/officeonline/index?fileId=118758&requesttoken=zjs0HtiKOlUFsDvDggFws3hvyCrL5jZAaWCdadPIk3A%3D%3ApllnRpH4eR1j4GGn2HgT2jEg8AGnkQMpMVWtPKOm9UU%3D&path=/*********/********************.pdf
from **************** by ****************** at 2021-01-08T11:25:14+02:00
```

#### Browser log
![oos](https://user-images.githubusercontent.com/51194757/104420283-4f54d080-5582-11eb-80a6-c888fbe3300b.png)

**Comment by hheinen** [comment]
We running into the same Problem. Nextcloud Featured PDF Viewer and Office Online (MS Office Online Integration) is activated. On the MS side of the word, everything works fine. You can open and edit Office-Docs. But as soon as you try to open a PDF, this will also be tried to open in MS Office Online, which finally results in an error.

NC-Version: 21
Office Online Integration: 1.0.3
PDF-Viewer: 2.1.0

**Comment by hheinen** [comment]
@siimaarmaa just found a fix/workaround/feature... 

If you want that PDFs will be opened through PDF Viewer, here is what I did:

*InstallationpathToNextcloud*/apps/officeonline/lib
Remove 
`'application/pdf', `
under MIMETYPES_OPTIONAL

I have no Idea if this is "the right way" to do it. But it works for me.

**Comment by koelle25** [comment]
Hi @siimaarmaa ,

could you reopen this issue? The method mentioned above (by hheinen) is merely a workaround.

It should be properly fixed in the app.  
One method could be to have the option in the settings screen to enable/disable opening PDFs with this app.

**Comment by siimaarmaa** [comment]
@koelle25 not need to open, this case is fixed.

**Comment by koelle25** [comment]
I don't think so.

We have Office Online and the PDF Viewer apps installed & enabled, but PDFs are being opened with Office Online.

Only if I removed the `'application/pdf'` line from the  `MIMETYPES_OPTIONAL` array (in [lib/Capabilities.php#L66](https://github.com/nextcloud/officeonline/blob/master/lib/Capabilities.php#L66)) PDFs are being opened in the PDF Viewer app.

**Comment by siimaarmaa** [comment]
@koelle25 i dont, my nextcloud have fixed this,

**Comment by siimaarmaa** [comment]
@koelle25 mime type i dint must remove, this only your problem. My problem solved with version update

**Comment by andyxheli** [comment]
Seems like this app dose not get frequent fixes and upgrades it's a shame 😞
