### ISSUE TITLE
Session times-out after 30 minutes

### ISSUE THREAD

**Issue by angstymeat** [nextcloud/officeonline#95]
**Describe the bug**
After 30 minutes, whether it's being used or not, Office Online reports "your session has expired" and you can no longer edit the document. Any edits in the last minute are lost.

This causes chaos when multiple users are working on a document together and they start timing out right after each other.

I can't find a setting in either Office Online or NextCloud to control this.

From the WOPI docs it looks like this is the expected behavior, except it should be using RefreshLock() to extend the work time. That doesn't appear to be happening.

**To Reproduce**
1. Open a document.
2. Wait 30 minutes

**Expected behavior**
You should be able to keep working until you close the document.

**Client details:**
 - OS:  Any OS
 - Browser Any Browser (tested firefox, opera, safari, and chrome)
 - Version: Any version
 - Device: Any device (failed on desktops and phones)

## Server details
CentOS 7, apache 2.24, php 7.3
Windows Server 2016, IIS & Office Online. All recent patches.

**Operating system**:
CentOS 7, apache 2.24, php 7.3
Windows Server 2016, IIS & Office Online. All recent patches.

**Web server:**
Apache 2.24
IIS

**Database:**
MariaDB 10.5

**PHP version:**
7.3.24

**Nextcloud version:**
20.0.6

**Version of the officeonline app**
1.0.2

**Version of Office Online server**
16.0.10338.20039

**Comment by finalls** [comment]
I have the same problem.
The connector or office must update file lock but it does not happen.

X-WOPI-Override – The string REFRESH_LOCK. Required.

**Comment by gurarl** [comment]
Hello, 
I have tge same problem too. 

Do you find solution or workaround?

**Comment by angstymeat** [comment]
I'm seeing that the locks in the `oc_officeonline_locks` table are being refreshed every ten minutes, extending the lock by 30 minutes. However, the token never gets extended. When the token expires, you can't edit anymore. However, since the file is still locked, we start seeing locking errors as others try to re-open and edit the file after the token expires. Expired tokens only seems to be removed from `oc_officeonline_wopi` when a new token is requested. Also, it seems that a lot of the time the lock isn't removed until the original opener of the file closes the window. This causes havoc periodically for us as we end up with files that stay locked data is lost as it seems there is fighting over the locks.

Currently, my workaround is a few things:

- I upgraded to PHP 7.4 and REFRESH_LOCK started getting called.
- I edited `lib/Db/WopiMapper.php` and changed `TOKEN_LIFETIME_SECONDS` to a longer lifetime (I set it to 4 hours).
- I put together a quick script that runs every 5 minutes and removes entries from `oc_officeonline_locks` that don't have a matching token in `oc_officeonline_wopi`.

So far, this allows the file to be opened long enough that it doesn't die in the middle of editing during group meetings. The 4 hour setting seems to set an upper-limit on the time the file can be opened, but because of the lock cleanup script I'm using, we don't seem to be having weird locking issues and data loss.

My edits are just a bunch of hacks to get this working in my organization. What I _think_ needs to be done:
- The token lifetime should be extended along with the lock lifetime when REFRESH_LOCK is called.
- Every time `oc_officeonline_locks` and `oc_officeonline_wopi` is updated, locks should be removed when the associated token is no longer being used in the wopi table. Also, all expired tokens should be removed from the wopi table whenever the table is read or written.

I haven't had the time to try editing the app to how these changes would affect it.

Also, I take no responsibility as to whether these would work or not in your setup. I just know that since I implemented these changes a week ago, we haven't had any errors or data loss in our configuration, and that was happening almost every day before.

**Comment by gurarl** [comment]
Thank you.
 I tried your workaround. It helped. 
Now the documents do not fall off during the meeting.

**Comment by juliushaertl** [comment]
Let's track this in https://github.com/nextcloud/officeonline/issues/155
