### ISSUE TITLE
An exception occurred while executing 'CREATE UNIQUE INDEX rd_wopi_token_idx ON oc_richdocuments_wopi (token)': SQLSTATE[42P07]: Duplicate table: 7 ERROR: relation "rd_wopi_token_idx" already exists

### ISSUE THREAD

**Issue by Deltafox01** [nextcloud/officeonline#99]
Hello,

Error:  "An exception occurred while executing 'CREATE UNIQUE INDEX rd_wopi_token_idx ON oc_richdocuments_wopi (token)': SQLSTATE[42P07]: Duplicate table: 7 ERROR: relation "rd_wopi_token_idx" already exists"

im getting this error while trying to install the App on our Nextcloud.

I have found the other BUG report (https://github.com/nextcloud/officeonline/pull/6) related to this error, but i dont see a solution for me and how to install the App Successfully?!

Thanks!"

**Comment by andyxheli** [comment]
@Deltafox01 Is this still an issue for you? If not can you please close the ticket ?

**Comment by Deltafox01** [comment]
> @Deltafox01 Is this still an issue for you? If not can you please close the ticket ?

Yes it is still an issue.

**Comment by andyxheli** [comment]
What your server setup look like? I not able to duplicate the issue and I'm be tried it in 4 different servers

**Comment by juliushaertl** [comment]
Can you try to remove the app itself from the app directory of your Nextcloud instance and try to re-download it from the App Store? The mentioned index should not be created anymore in the latest releases.

**Comment by andyxheli** [comment]
@Deltafox01 Where you able to try the solution from https://github.com/nextcloud/officeonline/issues/99#issuecomment-1062279978 ?

**Comment by juliushaertl** [comment]
Let's close this since this issue should not occur with the latest release. Let us you if you still encounter this.
